export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_SELECTED_BAR = 'SET_SELECTED_BAR';
export const GET_INITIAL_SELECTED_BAR = 'GET_INITIAL_SELECTED_BAR';

export const SET_SEARCH_LIST_SUCCESS = 'SET_SEARCH_LIST_SUCCESS';
export const SET_SEARCH_LIST_ERROR = 'SET_SEARCH_LIST_ERROR';
export const REQUEST_SEARCH_LIST = 'REQUEST_SEARCH_LIST';

export const SHOW_LOGINSCREEN = 'SHOW_LOGINSCREEN';
export const CLOSE_LOGINSCREEN = 'CLOSE_LOGINSCREEN';

export const RESET_SEARCH_LIST = 'RESET_SEARCH_LIST';
